boardgame_library/config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :designers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
end

boardgame_library/app/models/designer.rb
class Designer < ApplicationRecord
  has_many :games
  validates :name, presence: true
end

boardgame_library/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :designer, optional: true
end

boardgame_library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

boardgame_library/app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  before_action :set_designer, only: [:show, :edit, :update, :destroy]

  # GET /designers
  # GET /designers.json
  def index
    @designers = Designer.all
  end

  # GET /designers/1
  # GET /designers/1.json
  def show
  end

  # GET /designers/new
  def new
    @designer = Designer.new
  end

  # GET /designers/1/edit
  def edit
  end

  # POST /designers
  # POST /designers.json
  def create
    @designer = Designer.new(designer_params)

    respond_to do |format|
      if @designer.save
        format.html { redirect_to @designer, notice: 'Designer was successfully created.' }
        format.json { render :show, status: :created, location: @designer }
      else
        format.html { render :new }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designers/1
  # PATCH/PUT /designers/1.json
  def update
    respond_to do |format|
      if @designer.update(designer_params)
        format.html { redirect_to @designer, notice: 'Designer was successfully updated.' }
        format.json { render :show, status: :ok, location: @designer }
      else
        format.html { render :edit }
        format.json { render json: @designer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designers/1
  # DELETE /designers/1.json
  def destroy
    @designer.destroy
    respond_to do |format|
      format.html { redirect_to designers_url, notice: 'Designer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designer
      @designer = Designer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designer_params
      params.require(:designer).permit(:name, :company, :url, :photo_url)
    end
end

boardgame_library/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :min_players, :max_players, :min_duration, :max_duration, :min_age, :designer_id)
    end
end

boardgame_library/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

boardgame_library/app/helpers/application_helper.rb
module ApplicationHelper
end

boardgame_library/app/helpers/designers_helper.rb
module DesignersHelper
end

boardgame_library/app/helpers/games_helper.rb
module GamesHelper
end

boardgame_library/app/helpers/home_helper.rb
module HomeHelper
end

boardgame_library/app/views/designers/_form.html.erb
<%= form_with(model: designer, local: true) do |form| %>
  <% if designer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(designer.errors.count, "error") %> prohibited this designer from being saved:</h2>

      <ul>
      <% designer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :photo_url %>
    <%= form.text_field :photo_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

boardgame_library/app/views/designers/edit.html.erb
<h1>Editing Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Show', @designer %> |
<%= link_to 'Back', designers_path %>

boardgame_library/app/views/designers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designers</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Company</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designers.each do |designer| %>
      <tr>
        <td>
          <%= link_to designer do %>
            <img src="<%= designer.photo_url %>" height="100" />
          <% end %>
        </td>
        <td><%= link_to designer.name, designer %></td>
        <td><%= designer.company %></td>
        <td><a href="<%= designer.url %>"><%= designer.url %></a></td>
        <td><%= link_to 'Show', designer %></td>
        <td><%= link_to 'Edit', edit_designer_path(designer) %></td>
        <td><%= link_to 'Destroy', designer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Designer', new_designer_path %>

boardgame_library/app/views/designers/new.html.erb
<h1>New Designer</h1>

<%= render 'form', designer: @designer %>

<%= link_to 'Back', designers_path %>

boardgame_library/app/views/designers/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @designer.name %></h2>
<h3><%= @designer.company %></h3>

<a href="<%= @designer.url %>"><%= @designer.url %></a>

<p>
  <img src="<%= @designer.photo_url %>" />
</p>

<h2>Games by <%= @designer.name %></h2>

<ul>
  <% @designer.games.each do |game| %>
    <li><%= link_to game.name, game %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_designer_path(@designer) %> |
<%= link_to 'Back', designers_path %>

boardgame_library/app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :min_players %>
    <%= form.number_field :min_players %>
  </div>

  <div class="field">
    <%= form.label :max_players %>
    <%= form.number_field :max_players %>
  </div>

  <div class="field">
    <%= form.label :min_duration %>
    <%= form.number_field :min_duration %>
  </div>

  <div class="field">
    <%= form.label :max_duration %>
    <%= form.number_field :max_duration %>
  </div>

  <div class="field">
    <%= form.label :min_age %>
    <%= form.number_field :min_age %>
  </div>

  <div class="field">
    <%= form.label :designer_id %>
    <%= form.select :designer_id, Designer.all.map { |designer| [designer.name, designer.id] }, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

boardgame_library/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

boardgame_library/app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Players</th>
      <th>Duration</th>
      <th>Ages</th>
      <th>Designer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td>
          <% if game.min_players == game.max_players %>
            <%= game.min_players %>
          <% else %>
            <%= game.min_players %> - <%= game.max_players %>
          <% end %>
        </td>
        <td>
          <% if game.min_duration == game.max_duration %>
            <%= game.min_duration %>
          <% else %>
            <%= game.min_duration %> - <%= game.max_duration %>
          <% end %>
        </td>
        <td><%= game.min_age %>+</td>
        <td><%= link_to game.designer.name, game.designer if game.designer %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

boardgame_library/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

boardgame_library/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= link_to @game.name, @game %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Min players:</strong>
  <%= @game.min_players %>
</p>

<p>
  <strong>Max players:</strong>
  <%= @game.max_players %>
</p>

<p>
  <strong>Min duration:</strong>
  <%= @game.min_duration %>
</p>

<p>
  <strong>Max duration:</strong>
  <%= @game.max_duration %>
</p>

<p>
  <strong>Min age:</strong>
  <%= @game.min_age %>
</p>

<p>
  <strong>Designer:</strong>
  <% if @game.designer %>
    <%= link_to @game.designer.name, @game.designer %>
  <% end %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

boardgame_library/app/views/home/index.html.erb
<p>Welcome to our library.</p>

boardgame_library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boardgame Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Boardgame Library</h1>
      <nav>
        <ul>
          <li><%= link_to 'Designers', :designers %></li>
          <li><%= link_to 'Games', :games %></li>
        </ul>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <p>Made with ❤️ in St Petersburg, FL.</p>
    </footer>
  </body>
</html>